"""Make teamID nullable in membership for managers to assign later on

Revision ID: 62e8a73c4c16
Revises: a7c510f25433
Create Date: 2026-04-29 13:29:47.847026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e8a73c4c16'
down_revision: Union[str, Sequence[str], None] = 'a7c510f25433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('teamID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('teamID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
