"""initial_schema

Revision ID: a7c510f25433
Revises: 
Create Date: 2026-04-28 20:31:23.579792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c510f25433'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_summary',
    sa.Column('summaryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameName', sa.String(), nullable=False),
    sa.Column('teamName', sa.String(), nullable=False),
    sa.Column('ownTotal', sa.Integer(), nullable=False),
    sa.Column('oppTotal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('summaryID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_summary')
    # ### end Alembic commands ###
