"""initial migration

Revision ID: caa4bdd2c3b3
Revises: 
Create Date: 2026-05-02 02:54:31.303255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa4bdd2c3b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('playerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playerName', sa.String(), nullable=False),
    sa.Column('playerNumber', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('isVerified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('playerID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('player_result',
    sa.Column('summaryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameName', sa.String(), nullable=False),
    sa.Column('playerName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('summaryID')
    )
    op.create_table('team',
    sa.Column('teamID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teamName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('teamID')
    )
    op.create_table('team_result',
    sa.Column('summaryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameName', sa.String(), nullable=False),
    sa.Column('teamName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('summaryID')
    )
    op.create_table('membership',
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('player', 'manager', 'root', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['playerID'], ['player.playerID'], ),
    sa.ForeignKeyConstraint(['teamID'], ['team.teamID'], ),
    sa.PrimaryKeyConstraint('playerID')
    )
    op.create_table('player_event',
    sa.Column('summaryID', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('eventType', sa.String(), nullable=False),
    sa.Column('pointDelta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['summaryID'], ['player_result.summaryID'], ),
    sa.PrimaryKeyConstraint('summaryID', 'eventID')
    )
    op.create_table('team_event',
    sa.Column('summaryID', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('pointMethod', sa.String(), nullable=False),
    sa.Column('pointDelta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['summaryID'], ['team_result.summaryID'], ),
    sa.PrimaryKeyConstraint('summaryID', 'eventID')
    )
    op.create_table('verification',
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playerID'], ['player.playerID'], ),
    sa.PrimaryKeyConstraint('playerID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    op.drop_table('team_event')
    op.drop_table('player_event')
    op.drop_table('membership')
    op.drop_table('team_result')
    op.drop_table('team')
    op.drop_table('player_result')
    op.drop_table('player')
    # ### end Alembic commands ###
