"""Make membership's role column be only a set of values

Revision ID: d052b3fe2258
Revises: 62e8a73c4c16
Create Date: 2026-04-29 17:04:21.407556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd052b3fe2258'
down_revision: Union[str, Sequence[str], None] = '62e8a73c4c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
