"""initial migration

Revision ID: de9339b1a92a
Revises: 
Create Date: 2026-05-05 17:01:33.476211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9339b1a92a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('playerNumber', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('isVerified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('team',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('membership',
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('teamID', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('player', 'manager', 'root', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['playerID'], ['player.ID'], ),
    sa.ForeignKeyConstraint(['teamID'], ['team.ID'], ),
    sa.PrimaryKeyConstraint('playerID')
    )
    op.create_table('player_result',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('youtubeURL', sa.String(), nullable=False),
    sa.Column('gameName', sa.String(), nullable=True),
    sa.Column('playerID', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['playerID'], ['player.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('team_result',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('youtubeURL', sa.String(), nullable=False),
    sa.Column('gameName', sa.String(), nullable=True),
    sa.Column('teamID', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['teamID'], ['team.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('verification',
    sa.Column('playerID', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playerID'], ['player.ID'], ),
    sa.PrimaryKeyConstraint('playerID')
    )
    op.create_table('player_event',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('resultID', sa.Integer(), nullable=False),
    sa.Column('eventType', sa.String(), nullable=False),
    sa.Column('pointDelta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resultID'], ['player_result.ID'], ),
    sa.PrimaryKeyConstraint('ID', 'resultID')
    )
    op.create_table('team_event',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('resultID', sa.Integer(), nullable=False),
    sa.Column('pointMethod', sa.String(), nullable=False),
    sa.Column('pointDelta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resultID'], ['team_result.ID'], ),
    sa.PrimaryKeyConstraint('ID', 'resultID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_event')
    op.drop_table('player_event')
    op.drop_table('verification')
    op.drop_table('team_result')
    op.drop_table('player_result')
    op.drop_table('membership')
    op.drop_table('team')
    op.drop_table('player')
    # ### end Alembic commands ###
